pipeline:
  test:
    image: debian
    commands:
      - apt update --yes
      - apt install --yes curl git
      - curl --location https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb --output ../nvim.deb
      - git clone https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
      - apt install ../nvim.deb
      - ./scripts/test.sh

when:
  path:
    - .woodpecker.yml
    - lua/*
    - scripts/test.sh
    - tests/*
